# Whats is Numpy? 
        - Numerical Python: maths stats, sciences , physics
        - Its an array. Not similar to python list. 
        - Array holds uniform data type.

In [3]:
def squares(values):
    result = []
    for v in values:
        result.append(v * v)
    return result

In [5]:
to_square = range(100000)

In [6]:
%timeit squares(to_square)

21.3 ms ± 319 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
import numpy as np

In [8]:
lst = [1,2,3,4,5,6,7,8,9,10]
print(type(lst))

<class 'list'>


In [11]:
arr = np.array(lst) 
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [14]:
arr*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [16]:
arr = np.arange(100000)
%timeit arr**2

166 μs ± 20 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# Creating Numpy Arrays
    - numpy.array()
    - numpy.arange()
    - type cast python list

# 1D array

In [ ]:
arr = np.array(lst)
arr

In [19]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr = np.array((1,2,3,4))
arr

array([1, 2, 3, 4])

In [22]:
arr.size

4

In [23]:
arr.shape

(4,)

In [24]:
arr.dtype

dtype('int32')

In [27]:
lst = [1,2,3,4,5,'apple']

In [28]:
arr = np.array(lst)
arr

array(['1', '2', '3', '4', '5', 'apple'], dtype='<U11')

In [29]:
arr.ndim

1

In [34]:
lst = [1,2,3,4,5,6,7,8,9,10]
arr = np.array(lst)

In [35]:
arr+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
arr1 = np.arange(20,30)
arr1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
arr1 + arr

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

In [38]:
arr2 = np.arange(9)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (10,) (9,) 

# 2-D Array

In [40]:
lst  = [[1,2,3],[4,5,6],[7,8,9]]
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [42]:
arr2d = np.array(lst)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr2d.size

9

In [44]:
arr2d.shape

(3, 3)

In [45]:
arr2d.ndim

2

In [49]:
arr2d2 = np.arange(9).reshape(3,3)
arr2d2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
arr2d3 = np.arange(50).reshape(25,2)
arr2d3

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

In [57]:
arr3d = np.arange(27).reshape(3,3,3) # copy/Depth, Rows , Columns
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [63]:
arr = np.array([[10]])
arr.ndim

2

In [66]:
# Import the necessary libraries
from PIL import Image

# load the image and convert into
# numpy array
image = Image.open('pic.jpg')
print(type(image))
# asarray() class is used to convert
# PIL images into NumPy arrays
numpydata = np.asarray(image)

# <class 'numpy.ndarray'>
print(type(numpydata))

# shape
print(numpydata.shape)

numpydata

<class 'PIL.JpegImagePlugin.JpegImageFile'>
<class 'numpy.ndarray'>
(2003, 3000, 3)


array([[[ 53,  58,  54],
        [ 54,  59,  55],
        [ 55,  60,  56],
        ...,
        [227, 232, 235],
        [227, 232, 235],
        [227, 232, 235]],

       [[ 54,  59,  55],
        [ 54,  59,  55],
        [ 55,  60,  56],
        ...,
        [227, 232, 235],
        [227, 232, 235],
        [227, 232, 235]],

       [[ 55,  60,  56],
        [ 55,  60,  56],
        [ 55,  60,  56],
        ...,
        [227, 232, 235],
        [227, 232, 235],
        [227, 232, 235]],

       ...,

       [[187, 183, 172],
        [187, 183, 172],
        [188, 184, 173],
        ...,
        [129, 130, 132],
        [126, 127, 129],
        [125, 126, 128]],

       [[187, 183, 172],
        [187, 183, 172],
        [188, 184, 173],
        ...,
        [129, 130, 132],
        [126, 127, 129],
        [125, 126, 128]],

       [[187, 183, 172],
        [187, 183, 172],
        [188, 184, 173],
        ...,
        [129, 130, 132],
        [126, 127, 129],
        [125, 126, 128]]

In [67]:
arr = np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
arr[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr[5,7]

57

In [74]:
arr[5:6,7:8]

array([[57]])

In [75]:
arr[-1]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [78]:
arr[:, 9:]

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])

In [80]:
arr[:,5:6]

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55],
       [65],
       [75],
       [85],
       [95]])

In [81]:
numpydata

array([[[ 53,  58,  54],
        [ 54,  59,  55],
        [ 55,  60,  56],
        ...,
        [227, 232, 235],
        [227, 232, 235],
        [227, 232, 235]],

       [[ 54,  59,  55],
        [ 54,  59,  55],
        [ 55,  60,  56],
        ...,
        [227, 232, 235],
        [227, 232, 235],
        [227, 232, 235]],

       [[ 55,  60,  56],
        [ 55,  60,  56],
        [ 55,  60,  56],
        ...,
        [227, 232, 235],
        [227, 232, 235],
        [227, 232, 235]],

       ...,

       [[187, 183, 172],
        [187, 183, 172],
        [188, 184, 173],
        ...,
        [129, 130, 132],
        [126, 127, 129],
        [125, 126, 128]],

       [[187, 183, 172],
        [187, 183, 172],
        [188, 184, 173],
        ...,
        [129, 130, 132],
        [126, 127, 129],
        [125, 126, 128]],

       [[187, 183, 172],
        [187, 183, 172],
        [188, 184, 173],
        ...,
        [129, 130, 132],
        [126, 127, 129],
        [125, 126, 128]]

In [82]:
numpydata.shape

(2003, 3000, 3)

In [83]:
numpydata[10:, 10:, :]

array([[[ 54,  58,  59],
        [ 54,  58,  59],
        [ 54,  58,  59],
        ...,
        [228, 233, 236],
        [228, 233, 236],
        [228, 233, 236]],

       [[ 54,  58,  59],
        [ 54,  58,  59],
        [ 54,  58,  59],
        ...,
        [228, 233, 236],
        [228, 233, 236],
        [228, 233, 236]],

       [[ 54,  58,  59],
        [ 54,  58,  59],
        [ 54,  58,  59],
        ...,
        [228, 233, 236],
        [228, 233, 236],
        [228, 233, 236]],

       ...,

       [[187, 183, 172],
        [190, 186, 175],
        [191, 187, 176],
        ...,
        [129, 130, 132],
        [126, 127, 129],
        [125, 126, 128]],

       [[188, 184, 173],
        [191, 187, 176],
        [191, 187, 176],
        ...,
        [129, 130, 132],
        [126, 127, 129],
        [125, 126, 128]],

       [[189, 185, 174],
        [191, 187, 176],
        [191, 187, 176],
        ...,
        [129, 130, 132],
        [126, 127, 129],
        [125, 126, 128]]