In [1]:
import numpy as np

In [5]:
random_array = np.random.rand(5)
print(random_array)

[0.24723308 0.18068597 0.6870654  0.90962518 0.88335   ]


In [6]:
random_array = np.random.randn(5)
print(random_array)

[-0.05345889 -0.36830057  0.26569024  0.24045333 -0.24570766]


In [7]:
random_int_array = np.random.randint(10, 50, size=5)

In [8]:
print(random_int_array)

[13 47 28 18 31]


In [13]:
random_int_array >= 40

array([False,  True, False, False, False])

## Boolean Selection

## Masking