In [6]:
def squares(values):
    result = []
    for i in values:
        result.append(i**2)
    return result

In [7]:
to_square = range(100000)

In [11]:
# Magic Function to check time consume
%timeit squares(to_square)

23.5 ms ± 317 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# What is Numpy?
  - It is a Python Library
  - Numerial Python: math, stats, science, physics
  - Its an array. Not similar to python list
  - Array holds uniform data type.

In [12]:
import numpy as np

In [13]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [14]:
print(type(lst))

<class 'list'>


In [19]:
arr = np.array(lst)

In [20]:
print(arr)
print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [21]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [22]:
arr*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [23]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


array = vector

# 