# Combining arrays

In [2]:
import numpy as np

In [4]:
a = np.zeros((4,4))
b = np.ones((4,4))

In [5]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.hstack((a,b))

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [8]:
np.vstack((a,b))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
a = np.arange(16).reshape(4,4)
b = np.arange(16,32).reshape(4,4)

In [13]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
b

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [12]:
np.dstack((a,b))

array([[[ 0, 16],
        [ 1, 17],
        [ 2, 18],
        [ 3, 19]],

       [[ 4, 20],
        [ 5, 21],
        [ 6, 22],
        [ 7, 23]],

       [[ 8, 24],
        [ 9, 25],
        [10, 26],
        [11, 27]],

       [[12, 28],
        [13, 29],
        [14, 30],
        [15, 31]]])

In [15]:
np.concatenate((a, b), axis = 1)

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [16]:
np.concatenate((a, b), axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [19]:
np.column_stack((a,b))

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [20]:
np.row_stack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

# Splitting arrays

In [21]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [23]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [24]:
np.split(a, 2, axis = 1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [25]:
np.split(a, 2, axis = 0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# Useful numerical methods of NumPy arrays

In [32]:
m = np.array([[34,56,23],[2,76,8],[8,7,0]])
print (m)

[[34 56 23]
 [ 2 76  8]
 [ 8  7  0]]


In [27]:
print ("{0} min of the entire matrix".format(m.min()))

10 min of the entire matrix


In [28]:
print ("{0} max of entire matrix".format(m.max()))

18 max of entire matrix


In [29]:
print ("{0} position of the min value".format(m.argmin()))

0 position of the min value


In [30]:
print ("{0} position of the max value".format(m.argmax()))

8 position of the max value


In [33]:
print ("{0} mins down each column".format(m.min(axis = 0)))


[2 7 0] mins down each column


In [34]:
print ("{0} mins across each row".format(m.min(axis = 1)))

[23  2  0] mins across each row


In [35]:
print ("{0} maxs down each column".format(m.max(axis = 0)))

[34 76 23] maxs down each column


In [36]:
a.mean(), a.std(), a.var()

(7.5, 4.6097722286464435, 21.25)

In [ ]:
a.sum(), a.prod()

In [ ]:
a.cumsum(), a.cumprod()

In [37]:
(a < 5).any() , (a>5).all()

(True, False)

# Fancy Indexing

In [40]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
a[:,3:]

array([[ 3],
       [ 7],
       [11],
       [15]])

In [45]:
a[[3,0,2]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [46]:
a[:,[3,1,0]]

array([[ 3,  1,  0],
       [ 7,  5,  4],
       [11,  9,  8],
       [15, 13, 12]])

# Transposing Arrays and Swapping Axes

In [48]:
a.T , a.transpose()

(array([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]]),
 array([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]]))

# Universal Functions: Fast Element-Wise Array Functions

In [50]:
a =np.array([2.9, 2.1, 3.5])
np.ceil(a)

array([3., 3., 4.])

In [51]:
a =np.array([2.9, 2.1, 3.5])
np.floor(a)

array([2., 2., 3.])

# Sorting

# Unique and Other Set Logic

# Linear Algebra

In [52]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [53]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [55]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

# Mirror Operations

In [66]:
w  = np.arange(16).reshape(4,4)
z = np.arange(16,32).reshape(4,4)
t = np.arange(12).reshape(3,4)
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
z

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [65]:
w * z

array([[  0,  17,  36,  57],
       [ 80, 105, 132, 161],
       [192, 225, 260, 297],
       [336, 377, 420, 465]])

In [68]:
w + t

ValueError: operands could not be broadcast together with shapes (4,4) (3,4) 

In [69]:
w*t

ValueError: operands could not be broadcast together with shapes (4,4) (3,4) 

In [71]:
w@z

array([[ 152,  158,  164,  170],
       [ 504,  526,  548,  570],
       [ 856,  894,  932,  970],
       [1208, 1262, 1316, 1370]])

In [72]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [73]:
x@y

array([[ 28.,  64.],
       [ 67., 181.]])