## Combining Array
  - Horizontal Stack
  - Vertical Stack
  - Depth Stach

In [2]:
import numpy as np

In [5]:
a = np.zeros((4,4))
b = np.ones((4,4))

In [6]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.hstack((a,b))

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [10]:
np.vstack((a,b))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
print(a)
print(b)
np.dstack((a,b))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]]])

In [14]:
c = np.arange(16).reshape(4,4)

In [15]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
print(a)
print(b)
print(c)
np.dstack((a,b,c))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[[ 0.,  1.,  0.],
        [ 0.,  1.,  1.],
        [ 0.,  1.,  2.],
        [ 0.,  1.,  3.]],

       [[ 0.,  1.,  4.],
        [ 0.,  1.,  5.],
        [ 0.,  1.,  6.],
        [ 0.,  1.,  7.]],

       [[ 0.,  1.,  8.],
        [ 0.,  1.,  9.],
        [ 0.,  1., 10.],
        [ 0.,  1., 11.]],

       [[ 0.,  1., 12.],
        [ 0.,  1., 13.],
        [ 0.,  1., 14.],
        [ 0.,  1., 15.]]])