In [2]:
import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
scalar = 10  # Scalar value

result = array_2d + scalar

print(result)
print(array_2d)

[[11 12 13]
 [14 15 16]]
[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

# Broadcasting a 1D array with a 2D array
a1 = np.array([2, 4, 6])
a2 = np.array([[1, 3, 5], [7, 9, 11]])
a1

array([2, 4, 6])

In [4]:
a2

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [5]:
res = a1 + a2
print(res)

[[ 3  7 11]
 [ 9 13 17]]


In [6]:
import numpy as np
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])


In [7]:
matrix

array([[1, 2],
       [3, 4]])

In [8]:
vector

array([10, 20])

In [9]:
result = matrix * vector
print(result) 

[[10 40]
 [30 80]]


In [11]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])


In [14]:
print(x)
x.shape

[[1]
 [2]
 [3]]


(3, 1)

In [15]:
print(y)
y.shape

[4 5 6]


(3,)

In [16]:
b = np.broadcast(x,y)
b

In [17]:
out = np.empty(b.shape)

In [18]:
out

array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 9.17e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [27]:
out.flat = [u+v for (u,v) in b]
out

array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

# List comprehension

In [19]:
lst = [1,2,3,4]
new = []
for a in lst:
    new.append(a*10)

In [20]:
new

[10, 20, 30, 40]

In [22]:
lst = [1,2,3,4]

for i, a in enumerate(lst):
    lst[i] = a*10

lst

[10, 20, 30, 40]

In [23]:
[a*10 for a in range(10)]

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [25]:
[a*10  for a in range(10) if a%2==0]

[0, 20, 40, 60, 80]

In [26]:
[a*10 if a%2==0 else a*3 for a in range(10) ]

[0, 3, 20, 9, 40, 15, 60, 21, 80, 27]

# Dic Comprehenstion

In [29]:
{a:a**2 for a in range(1,10)}

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

# Pandas 
   ## Pandas Data Structures
            - Pandas Series : When dealing with single column data
            - Pandas DataFrame : When data has multiple columns

### Create Series

In [30]:
import pandas as pd

In [31]:
s1 = pd.Series([12,24,36,12,6,0,12,36])
s1

0    12
1    24
2    36
3    12
4     6
5     0
6    12
7    36
dtype: int64

In [32]:
s1.index

RangeIndex(start=0, stop=8, step=1)

In [33]:
s1.values

array([12, 24, 36, 12,  6,  0, 12, 36], dtype=int64)

In [34]:
type(s1)

pandas.core.series.Series

In [35]:
s1.dtype

dtype('int64')

# Customize indices : Labels

In [36]:
s1.index = ['Apples', 'Eggs', 'Breads',"Bananas", 'Mangoes', "Grapes", 'Peech', 'Lemon']

In [37]:
s1

Apples     12
Eggs       24
Breads     36
Bananas    12
Mangoes     6
Grapes      0
Peech      12
Lemon      36
dtype: int64

In [38]:
s1.name ="Fruits"

In [39]:
s1

Apples     12
Eggs       24
Breads     36
Bananas    12
Mangoes     6
Grapes      0
Peech      12
Lemon      36
Name: Fruits, dtype: int64

# Selecting / Retreiveing data from a series

In [40]:
s1['Grapes']

0

In [41]:
s1['Lemon']

36

In [42]:
s1["Eggs": "Grapes"]

Eggs       24
Breads     36
Bananas    12
Mangoes     6
Grapes      0
Name: Fruits, dtype: int64

In [43]:
s1[1:5]

Eggs       24
Breads     36
Bananas    12
Mangoes     6
Name: Fruits, dtype: int64

In [44]:
s1.shape

(8,)

# Data Frame

In [48]:
df = pd.DataFrame({'name':['Ali','Usman','Raza','Shani'],
                  'age':[18,64,17,23]})

In [50]:
df

name  age
0    Ali   18
1  Usman   64
2   Raza   17
3  Shani   23

In [51]:
df.shape

(4, 2)

In [52]:
df['Status'] = ['Live','Dead','Live', "Live"]
df

name  age Status
0    Ali   18   Live
1  Usman   64   Dead
2   Raza   17   Live
3  Shani   23   Live

In [53]:
df['Gender'] = ['Male','Female','Male','Female']
df

name  age Status  Gender
0    Ali   18   Live    Male
1  Usman   64   Dead  Female
2   Raza   17   Live    Male
3  Shani   23   Live  Female

In [54]:
del df['Status']
df

name  age  Gender
0    Ali   18    Male
1  Usman   64  Female
2   Raza   17    Male
3  Shani   23  Female

In [56]:
data = pd.read_excel("employee.xlsx",index_col="Serial")
data

Emp_ID Designation  Department   Age    Salary
Serial                                                
1         1101     Manager    Accounts  50.0  200000.0
2         1107     Officer          IT  30.0   80000.0
3         1203     Officer          HR  28.0       NaN
4         1005     Manager          HR  45.0  120000.0
5         2123  Office Boy    Accounts  27.0   45000.0
6         2451  Accountant         NaN  34.0  100000.0
7         1111  Accountant    Accounts   NaN  110000.0
8         1001     Officer          IT  25.0   75000.0
9         1234     Manager          IT  23.0       NaN
10        2156    Engineer  Production  45.0   89000.0
11        6543     Officer  Production  29.0  100000.0
12        3214  Accountant     Account  49.0  123000.0
13        2156    Engineer  Production  45.0   89000.0
14        1098     Officer          IT  25.0  100000.0
15        2912     Officer          IT  31.0   90000.0
16        1222     Officer         NaN  25.0       NaN
17        2156    Engineer  Production  45.0   89000.0
18        2123  Office Boy    Accounts  27.0   45000.0

# Acessing a single column from data 

In [57]:
data['Designation']

Serial
1        Manager
2        Officer
3        Officer
4        Manager
5     Office Boy
6     Accountant
7     Accountant
8        Officer
9        Manager
10      Engineer
11       Officer
12    Accountant
13      Engineer
14       Officer
15       Officer
16       Officer
17      Engineer
18    Office Boy
Name: Designation, dtype: object

In [58]:
type(data['Designation'])

pandas.core.series.Series

# Accessing mltiple columns 

In [59]:
data.columns

Index(['Emp_ID', 'Designation', 'Department', 'Age', 'Salary'], dtype='object')

In [61]:
data[['Emp_ID', 'Salary']]

Emp_ID    Salary
Serial                  
1         1101  200000.0
2         1107   80000.0
3         1203       NaN
4         1005  120000.0
5         2123   45000.0
6         2451  100000.0
7         1111  110000.0
8         1001   75000.0
9         1234       NaN
10        2156   89000.0
11        6543  100000.0
12        3214  123000.0
13        2156   89000.0
14        1098  100000.0
15        2912   90000.0
16        1222       NaN
17        2156   89000.0
18        2123   45000.0

In [62]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 1 to 18
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Emp_ID       18 non-null     int64  
 1   Designation  18 non-null     object 
 2   Department   16 non-null     object 
 3   Age          17 non-null     float64
 4   Salary       15 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 864.0+ bytes


In [63]:
data.shape

(18, 5)

In [64]:
data.head()

Emp_ID Designation Department   Age    Salary
Serial                                               
1         1101     Manager   Accounts  50.0  200000.0
2         1107     Officer         IT  30.0   80000.0
3         1203     Officer         HR  28.0       NaN
4         1005     Manager         HR  45.0  120000.0
5         2123  Office Boy   Accounts  27.0   45000.0

In [65]:
data.tail()

Emp_ID Designation  Department   Age    Salary
Serial                                                
14        1098     Officer          IT  25.0  100000.0
15        2912     Officer          IT  31.0   90000.0
16        1222     Officer         NaN  25.0       NaN
17        2156    Engineer  Production  45.0   89000.0
18        2123  Office Boy    Accounts  27.0   45000.0

In [66]:
data.sample(5)

Emp_ID Designation  Department   Age    Salary
Serial                                                
14        1098     Officer          IT  25.0  100000.0
13        2156    Engineer  Production  45.0   89000.0
1         1101     Manager    Accounts  50.0  200000.0
2         1107     Officer          IT  30.0   80000.0
15        2912     Officer          IT  31.0   90000.0

# Generate Data from data 

In [71]:
data.Salary = data.Salary+data.Salary*0.10

In [72]:
data

Emp_ID Designation  Department   Age    Salary
Serial                                                
1         1101     Manager    Accounts  50.0  215000.0
2         1107     Officer          IT  30.0   83000.0
3         1203     Officer          HR  28.0       NaN
4         1005     Manager          HR  45.0  127000.0
5         2123  Office Boy    Accounts  27.0   44500.0
6         2451  Accountant         NaN  34.0  105000.0
7         1111  Accountant    Accounts   NaN  116000.0
8         1001     Officer          IT  25.0   77500.0
9         1234     Manager          IT  23.0       NaN
10        2156    Engineer  Production  45.0   92900.0
11        6543     Officer  Production  29.0  105000.0
12        3214  Accountant     Account  49.0  130300.0
13        2156    Engineer  Production  45.0   92900.0
14        1098     Officer          IT  25.0  105000.0
15        2912     Officer          IT  31.0   94000.0
16        1222     Officer         NaN  25.0       NaN
17        2156    Engineer  Production  45.0   92900.0
18        2123  Office Boy    Accounts  27.0   44500.0

In [74]:
data['Salary_tax']= [salary*0.10 if salary>=200000 else salary*.08 if salary>=150000 else salary*.05 if salary>=100000 else salary*.03 if salary>=50000 else salary for salary in data.Salary]

In [75]:
data

Emp_ID Designation  Department   Age    Salary  Salary_tax
Serial                                                            
1         1101     Manager    Accounts  50.0  215000.0     21500.0
2         1107     Officer          IT  30.0   83000.0      2490.0
3         1203     Officer          HR  28.0       NaN         NaN
4         1005     Manager          HR  45.0  127000.0      6350.0
5         2123  Office Boy    Accounts  27.0   44500.0     44500.0
6         2451  Accountant         NaN  34.0  105000.0      5250.0
7         1111  Accountant    Accounts   NaN  116000.0      5800.0
8         1001     Officer          IT  25.0   77500.0      2325.0
9         1234     Manager          IT  23.0       NaN         NaN
10        2156    Engineer  Production  45.0   92900.0      2787.0
11        6543     Officer  Production  29.0  105000.0      5250.0
12        3214  Accountant     Account  49.0  130300.0      6515.0
13        2156    Engineer  Production  45.0   92900.0      2787.0
14        1098     Officer          IT  25.0  105000.0      5250.0
15        2912     Officer          IT  31.0   94000.0      2820.0
16        1222     Officer         NaN  25.0       NaN         NaN
17        2156    Engineer  Production  45.0   92900.0      2787.0
18        2123  Office Boy    Accounts  27.0   44500.0     44500.0

In [ ]:
data.